import {
  cols,
  Config,
  date,
  money,
  opts,
  source,
  text,
} from "../../shared/resource-config";
export const OrderConfig: Config = {
  title: "订单管理",
  description: "管理租赁订单，跟进收款、合同及交还进度",
  fields: [
    {
      ...source("unitId", "租赁单位", "units"),
      createOnly: true,
    },
    {
      ...source("salesUserId", "负责销售", "sales-users"),
      createOnly: true,
    },
    {
      key: "tenantType",
      label: "租客类型",
      type: "select",
      options: opts({
        PERSON: "个人",
        COMPANY: "公司",
      }),
      initial: "PERSON",
      required: true,
    },
    text("tenantName", "租客 / 公司名称", true),
    {
      key: "registrationNoType",
      label: "注册号码类型",
      type: "select",
      options: opts({
        BR: "商业登记号码",
        CR: "公司注册号码",
        HKID: "香港身份证",
        PASSPORT: "护照",
      }),
    },
    text("tenantRegistrationNo", "证件 / 商业登记号码"),
    text("tenantContactName", "联系人"),
    text("tenantPhone", "联系电话"),
    text("tenantEmail", "电子邮箱"),
    date("startsOn", "租期开始"),
    date("endsOn", "租期结束"),
    money("monthlyRent", "成交月租"),
    money("depositAmount", "押金"),
    {
      key: "depositPlan",
      label: "押付方式",
      type: "select",
      options: opts({
        ONE_ONE: "押一付一",
        TWO_ONE: "押二付一",
        THREE_ONE: "押三付一",
        OTHER: "其他",
      }),
    },
    date("moveInOn", "办理入住日期"),
    {
      key: "paymentIntervalMonths",
      label: "付款周期（月）",
      type: "number",
      initial: 1,
    },
    {
      key: "rentDueDay",
      label: "每月到期日",
      type: "number",
      initial: 1,
    },
    {
      key: "billLeadDays",
      label: "提前出账天数",
      type: "number",
      initial: 7,
    },
    {
      key: "firstPeriodProration",
      label: "首期按实际天数折算",
      type: "switch",
      initial: true,
    },
    {
      key: "lastPeriodProration",
      label: "末期按实际天数折算",
      type: "switch",
      initial: true,
    },
    {
      key: "remark",
      label: "订单备注",
      type: "textarea",
      span: 2,
    },
  ],
  columns: cols({
    orderNo: "订单编号",
    tenantName: "租客",
    projectName: "项目",
    unitNo: "单位",
    monthlyRent: "月租",
    startsOn: "租期开始",
    endsOn: "租期结束",
    status: "订单状态",
  }),
};
